version: "2"

services:

  styleguide:
        build: .
        image: hod-styleguide:latest
        ports:
          - "80:3000"
        volumes:
          - ./_scss:/app/_scss
          - ./_project:/app/_project
          - ./_layouts:/app/_layouts
          - ./_includes:/app/_includes
          - ./_common:/app/_common
        command: "gulp"
